# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  db_user: <%= ENV["DB_USER"] %>
  db_pass: <%= ENV["DB_PASS"] %>
  db_host: <%= ENV["DB_HOST"] %>
  db_name: <%= ENV["DB_NAME"] %>

development:
  <<: *common
  secret_key_base: 87146265db42d30f4bf478008a2419f07f41a52504d82d8214071c33607bfee0691cdd74a7e89bab99a04bebaae7acd486e077c139b9e680ef0e2dc217a6fe6c

test:
  <<: *common
  secret_key_base: 9b7f9e41ba423a85207b54e3e0126bff5b34f1a2bd3739a0a3b39c8f2fa04007038d6756a123e3b528e0b7149dc8d6af72006084dc61f37057ff187ea4c41cf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

